### ISSUE TITLE
blank icons in demo page

### ISSUE THREAD

**Issue by Delave-las-Kure** [jossef/material-design-icons-iconfont#22]
Version 4.02 is missing a lot of icons
![image](https://user-images.githubusercontent.com/24542423/48584365-9a3f1300-e93a-11e8-90d0-27b5d4bb6b9a.png)

**Comment by jossef** [comment]
Thanks for reporting.

I serve in this repo the officially (compiled by Google) font artifacts. Since the forked repo is abandoned, I scrape the most updated compiled fonts AS-IS straight from Google Fonts CDN (see my `build.py` script, I literally scrape & crossing variant user-agents)

opened #20 to customize and properly compile these webfonts
PR's are blessed!!! help-wanted

**Comment by jossef** [comment]
icons are not blank after added a ligature scraping to this story
fixed in latest version
