### ISSUE TITLE
Missing icons in "browser"

### ISSUE THREAD

**Issue by bterriervm** [jossef/material-design-icons-iconfont#23]
Some icons are missing in the list: https://jossef.github.io/material-design-icons-iconfont/

For instance `file_upload` and `file_download`.

Note that they are also missing from the official website (https://material.io/tools/icons/), but they were present in the previous versions of the website.

**Comment by jossef** [comment]
Thanks for reporting.

I serve in this repo the officially (compiled by Google) font artifacts. Since the forked repo is abandoned, I scrape the most updated compiled fonts AS-IS straight from Google Fonts CDN (see my `build.py` script, I literally scrape & crossing variant user-agents)

opened #20 to customize and properly compile these webfonts
PR's are blessed!!! help-wanted

**Comment by bterriervm** [comment]
The `file_download` icon is present in the fonts served by Google Fonts.
For instance `<mat-icon>file_download</mat-icon>` works perfectly.

It seems it is only missing from the "web icon browser". How it this page generated?

**Comment by jossef** [comment]
@bterriervm 

You are correct, this is a proof:
https://jsfiddle.net/jossef/nedoy8k6/2/

This list you see in my demo page is driven by the `json` file I took from https://material.io/tools/icons/static/data.json

as you mentioned, the `file_download` and `file_upload` are not presented in this json

will patch it
