### ISSUE TITLE
Broken icons if document fonts are disabled in Firefox

### ISSUE THREAD

**Issue by fabianski7** [jossef/material-design-icons-iconfont#67]
#### Actual behaviour
Using some modification script for firefox, such as ghacks/user.js (to improve security and privacy of the browser), causes the icons not to be displayed and the extension to get messy.

#### Steps to reproduce

1. Open the advanced firefox preferences (`about:config`) and change the `browser.display.use_document_fonts` option from `1` to `0`
2. Open some extension or site that use those icons 
2.1 https://jossef.github.io/material-design-icons-iconfont/ [[Screenshot](https://upload.vaa.red/jeme7#HYDVfQNXBzxLX9tYFKWY6jaK3bM29UGJ)]
2.2 [QOwnNotes firefox extension](https://addons.mozilla.org/pt-BR/firefox/addon/qownnotes-web-companion/) [[Screenshot](https://upload.vaa.red/2dnSjn#MbeTMFB350GKR4BhTJtZ0VL1WrsEyrr9)]

https://github.com/qownnotes/web-companion/issues/25

**Comment by jossef** [comment]
🤔 

I don't know if I can offer a fix for such configuration
suggestions?

**Comment by fabianski7** [comment]
in the related issue, that I created on qownnotes, there are some examples of how this was resolved
qownnotes/web-companion#25

**Comment by jossef** [comment]
@fabianski7 
1) sorry for the late response, my day job is extremely time consuming and I have very little time to contribute as before to this project
2) I have a solution for you. in [the demo application](https://jossef.github.io/material-design-icons-iconfont/), toggle the "CSS CLASSES"


instead of this form
```
<i class="material-icons">2k_plus</i>
<i class="material-icons">account_box</i>
...
```
use this form
```
<i class="material-icons _2k_plus"></i>
<i class="material-icons account_box"></i>
...
```

![image](https://user-images.githubusercontent.com/1287098/91716447-58776f00-eb98-11ea-8066-80c371b00917.png)

I've edited in `F12 Developer Tools`  inline HTML as a proof on firefox with this setting enabled

![image](https://user-images.githubusercontent.com/1287098/91716198-cec7a180-eb97-11ea-98a2-3e20683540a4.png)

TBD for me - will set the demo page when switching to css classes to also reflect on the displayed items
will update the demo and close this issue
